### ISSUE TITLE
샘플 능력 적용이 안되는거 같습니다

### ISSUE THREAD

**Issue by sgkill6** [monun/psychics#11]
아래처럼 오류창이 뜹니다 해결방법이 있나요?
[18:34:55 INFO]: sgkill6 issued server command: /psy reload
[18:34:55 INFO]: [Psychics] Updated abilities(0):
[18:34:56 INFO]: [Psychics] Loaded abilities(4):
[18:34:56 INFO]: [Psychics]   - com.github.monun.boomerang v0.0.1
[18:34:56 INFO]: [Psychics]   - com.github.monun.flying-sword v0.0.1
[18:34:56 INFO]: [Psychics]   - com.github.monun.magic-arrow v0.0.1
[18:34:56 INFO]: [Psychics]   - com.github.monun.straight-shuriken v0.0.1
[18:34:56 WARN]: java.lang.IllegalStateException: Not found ability com.github.noonmaru.boomerang
[18:34:56 WARN]:        at com.github.monun.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:224)
[18:34:56 WARN]:        at com.github.monun.psychics.PsychicManager.reload$psychics_common(PsychicManager.kt:62)
[18:34:56 WARN]:        at com.github.monun.psychics.plugin.PsychicPlugin.reloadPsychics(PsychicPlugin.kt:114)
[18:34:56 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:101)
[18:34:56 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:41)
[18:34:56 WARN]:        at com.github.monun.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[18:34:56 WARN]:        at com.github.monun.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[18:34:56 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:34:56 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:34:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[18:34:56 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
[18:34:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[18:34:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[18:34:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[18:34:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[18:34:56 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[18:34:56 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$5736/0x00000000d40f6a38.run(Unknown Source)
[18:34:56 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3667/0x00000000d6b2d330.run(Unknown Source)
[18:34:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:883)
[18:34:56 WARN]: [Psychics] Failed to load Psychic boomerang.yml
[18:34:56 WARN]: java.lang.IllegalStateException: Not found ability com.github.noonmaru.flying-sword
[18:34:56 WARN]:        at com.github.monun.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:224)
[18:34:56 WARN]:        at com.github.monun.psychics.PsychicManager.reload$psychics_common(PsychicManager.kt:62)
[18:34:56 WARN]:        at com.github.monun.psychics.plugin.PsychicPlugin.reloadPsychics(PsychicPlugin.kt:114)
[18:34:56 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:101)
[18:34:56 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:41)
[18:34:56 WARN]:        at com.github.monun.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[18:34:56 WARN]:        at com.github.monun.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[18:34:56 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:34:56 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:34:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[18:34:56 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
[18:34:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[18:34:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[18:34:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[18:34:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[18:34:56 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[18:34:56 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$5736/0x00000000d40f6a38.run(Unknown Source)
[18:34:56 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3667/0x00000000d6b2d330.run(Unknown Source)
[18:34:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:883)
[18:34:56 WARN]: [Psychics] Failed to load Psychic flying-sword.yml
[18:34:56 WARN]: java.lang.IllegalStateException: Not found ability com.github.noonmaru.magic-arrow
[18:34:56 WARN]:        at com.github.monun.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:224)
[18:34:56 WARN]:        at com.github.monun.psychics.PsychicManager.reload$psychics_common(PsychicManager.kt:62)
[18:34:56 WARN]:        at com.github.monun.psychics.plugin.PsychicPlugin.reloadPsychics(PsychicPlugin.kt:114)
[18:34:56 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:101)
[18:34:56 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:41)
[18:34:56 WARN]:        at com.github.monun.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[18:34:56 WARN]:        at com.github.monun.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[18:34:56 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:34:56 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:34:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[18:34:56 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
[18:34:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[18:34:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[18:34:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[18:34:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[18:34:56 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[18:34:56 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$5736/0x00000000d40f6a38.run(Unknown Source)
[18:34:56 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3667/0x00000000d6b2d330.run(Unknown Source)
[18:34:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:883)
[18:34:56 WARN]: [Psychics] Failed to load Psychic magic-arrow.yml
[18:34:56 WARN]: java.lang.IllegalStateException: Not found ability com.github.noonmaru.straight-shuriken
[18:34:56 WARN]:        at com.github.monun.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:224)
[18:34:56 WARN]:        at com.github.monun.psychics.PsychicManager.reload$psychics_common(PsychicManager.kt:62)
[18:34:56 WARN]:        at com.github.monun.psychics.plugin.PsychicPlugin.reloadPsychics(PsychicPlugin.kt:114)
[18:34:56 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:101)
[18:34:56 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:41)
[18:34:56 WARN]:        at com.github.monun.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[18:34:56 WARN]:        at com.github.monun.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[18:34:56 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:34:56 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:34:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[18:34:56 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
[18:34:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[18:34:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[18:34:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[18:34:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[18:34:56 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[18:34:56 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$5736/0x00000000d40f6a38.run(Unknown Source)
[18:34:56 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[18:34:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[18:34:56 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3667/0x00000000d6b2d330.run(Unknown Source)
[18:34:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:883)
[18:34:56 WARN]: [Psychics] Failed to load Psychic straight-shuriken.yml
[18:34:56 INFO]: [Psychics] Loaded psychics(0):
[18:34:56 INFO]: Psychics reload complete.

**Comment by myoun** [comment]
psychics 폴더 안에 있는 능력 yml 파일 보여주실래요?

**Comment by dytroInc** [comment]
pyschics이 0개군요.

plugins/Psychics/psychics에 .yml을 붙이고

abilities:
  (이름):
    ability: .(능력 이름)
    
으로 해야합니다.

**Comment by dytroInc** [comment]
그리고 에러 보니까, gradlew.properties라는 파일의 group 이름을 뭐로 했죠?

**Comment by sgkill6** [comment]
플러그인 예전꺼였네요 죄송합니다
