### ISSUE TITLE
능력 정보 확인시 오류발생

### ISSUE THREAD

**Issue by hyunjong0124** [monun/psychics#12]
콘솔에 뜨는 오류

[11:05:58 WARN]: java.lang.NoClassDefFoundError: com/github/monun/invfx/InvFX
[11:05:58 WARN]:        at com.github.monun.psychics.invfx.InvPsychic.create(InvPsychic.kt:20)
[11:05:58 WARN]:        at com.github.monun.psychics.command.CommandPsychic.info(CommandPsychic.kt:109)
[11:05:58 WARN]:        at com.github.monun.psychics.command.CommandPsychic.access$info(CommandPsychic.kt:41)
[11:05:58 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$4$2$1.invoke(CommandPsychic.kt:77)
[11:05:58 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$4$2$1.invoke(CommandPsychic.kt:41)
[11:05:58 WARN]:        at com.github.monun.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[11:05:58 WARN]:        at com.github.monun.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[11:05:58 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:05:58 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[11:05:58 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134)
[11:05:58 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[11:05:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by dytroInc** [comment]
마크 서버 버전 무엇을 사용했나요?
만약에 1.17보다 밑이면, 적용이 안 됩니다.

**Comment by dytroInc** [comment]
이번에 리뉴얼된 psychics 1.17이상만 지원됩니다
