### ISSUE TITLE
능력정보 확인시 오류발생 

### ISSUE THREAD

**Issue by mangchi123** [monun/psychics#19]
/psy info
[22:48:20 WARN]: java.lang.NoClassDefFoundError: com/github/monun/invfx/InvFX
[22:48:20 WARN]:        at com.github.monun.psychics.invfx.InvPsychic.create(InvPsychic.kt:20)
[22:48:20 WARN]:        at com.github.monun.psychics.command.CommandPsychic.info(CommandPsychic.kt:109)
[22:48:20 WARN]:        at com.github.monun.psychics.command.CommandPsychic.access$info(CommandPsychic.kt:41)
[22:48:20 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$4$3.invoke(CommandPsychic.kt:85)
[22:48:20 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$4$3.invoke(CommandPsychic.kt:41)
[22:48:20 WARN]:        at com.github.monun.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[22:48:20 WARN]:        at com.github.monun.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[22:48:20 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:48:20 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[22:48:20 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[22:48:20 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2165)
[22:48:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1976)
[22:48:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1957)
[22:48:20 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[22:48:20 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[22:48:20 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[22:48:20 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:48:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[22:48:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[22:48:20 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[22:48:20 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[22:48:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[22:48:20 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[22:48:20 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[22:48:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[22:48:20 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[22:48:20 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[22:48:20 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[22:48:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[22:48:20 WARN]: Caused by: java.lang.ClassNotFoundException: com.github.monun.invfx.InvFX
[22:48:20 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[22:48:20 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[22:48:20 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[22:48:20 WARN]:        ... 29 more
[22:48:24 WARN]: Can't keep up! Is the server overloaded? Running 5155ms or 103 ticks behind
버전 1.17.1로 했고 페이퍼로 했습니다

**Comment by dytroInc** [comment]
plugin.yml과 build.gradle.kts 둘 다 보내줄 수 있나요?

**Comment by mangchi123** [comment]
재가 release에서 1.0.1로 플러그인을 받아서 했습니다 빌드하는 방법을 잘모르겠었가주고

**Comment by dytroInc** [comment]
IntelliJ IDEA 사용하시면 Gradle 창에, pyschics-core라는 모듈에서 paperJar 하시면 됩니다.

**Comment by mangchi123** [comment]
아 감사합니다 해볼겠습니다.

**Comment by mangchi123** [comment]
pyschics-core라는 모듈에서 무엇을 눌러야 paperJar이 나오나요?

**Comment by dytroInc** [comment]
other

**Comment by mangchi123** [comment]
paperJar를 찾고 무엇을 해야하나요?

**Comment by mangchi123** [comment]
Run을 누르면 돼나요?

> other

**Comment by mangchi123** [comment]
아 플러그인은 됐는데 능력은 또 어떡해해야하나요?

**Comment by dytroInc** [comment]
> 아 플러그인은 됐는데 능력은 또 어떡해해야하나요?

전이랑 비슷한데, psychics-core 말고 psychics-abilities로 하세요

**Comment by mangchi123** [comment]
> > 아 플러그인은 됐는데 능력은 또 어떡해해야하나요?
> 
> 전이랑 비슷한데, psychics-core 말고 psychics-abilities로 하세요

그럼 psychics-core 에서 빌드한게 플러그인인가요? 플러그인으로 해봤는데 작동을 안해요

**Comment by dytroInc** [comment]
ㄴㄴ, plugins/Psychics/abilities에 있어야합니다

**Comment by mangchi123** [comment]
> ㄴㄴ, plugins/Psychics/abilities에 있어야합니다

플러그인 적용 완료하고 능력 적용을 하고싶은데 2개이상 적용이 안됍니다

**Comment by dytroInc** [comment]
> > ㄴㄴ, plugins/Psychics/abilities에 있어야합니다
> 
> 위키에서 능력을 만들떄 MyAbility 파일을 열어서 클래스를 만들고 com.github.noonmaru.psychics.Ability를 상속하세요 이런말이 무슨말인가요?

저건 outdate 된 코드입니다

**Comment by dytroInc** [comment]
쉽게 말해, 옛날 코드입니다

**Comment by mangchi123** [comment]
아그럼 능력을 만들려면 어떻게 해야하나요?

**Comment by qogusdn1017** [comment]
능력제작은 곧 공식/비공식 Wiki가 나올것 같습니다.
라이브러리를 보시면서 직접 배우실수도 있습니다.
해결되셨다면 이슈 닫아주세요.

**Comment by heisenberg-cat** [comment]
이슈 닫아주세요

**Comment by mangchi123** [comment]
해결했습니다 감사합니다
