### ISSUE TITLE
저만 안되나요

### ISSUE THREAD

**Issue by qasde741** [monun/psychics#2]
저는 각별님이 올려주신 자바 파일 적용을 해보았는데 안 됩니다. 게속해서 Dependency plugin 파일들을 다시 깔아보고 했지만 안되어 글을 올려봅니다 

> 

> C:\Users\이름\Desktop\다운로드\asdasd>java -Xms1G -Xmx2G -jar paper-1.16.5-467.jar

System Info: Java 1.8 (Java HotSpot(TM) 64-Bit Server VM 25.271-b09) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[06:22:44 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[06:22:44 INFO]: Found new data pack file/bukkit, loading it automatically
[06:22:44 INFO]: Reloading ResourceManager: Default, bukkit
[06:22:45 INFO]: Loaded 7 recipes
[06:22:46 INFO]: Starting minecraft server version 1.16.5
[06:22:46 INFO]: Loading properties
[06:22:46 INFO]: This server is running Paper version git-Paper-467 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[06:22:46 INFO]: Debug logging is disabled
[06:22:46 INFO]: Server Ping Player Sample Count: 12
[06:22:46 INFO]: Using 4 threads for Netty based IO
[06:22:46 INFO]: Default game type: SURVIVAL
[06:22:46 INFO]: Generating keypair
[06:22:46 INFO]: Starting Minecraft server on *:25565
[06:22:46 INFO]: Using default channel type
[06:22:47 ERROR]: Could not load 'plugins\Kotlin-1.4.30.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/github/noonmaru/kotlin/plugin/KotlinPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.5.jar:git-Paper-467]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Paper-467]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.5.jar:git-Paper-467]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.5.jar:git-Paper-467]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.5.jar:git-Paper-467]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-467]        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-467]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.UnsupportedClassVersionError: com/github/noonmaru/kotlin/plugin/KotlinPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_271]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:178) ~[patched_1.16.5.jar:git-Paper-467]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.5.jar:git-Paper-467]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[patched_1.16.5.jar:git-Paper-467]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-467]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_271]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_271]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.5.jar:git-Paper-467]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-467]
        ... 7 more
[06:22:47 ERROR]: Could not load 'plugins\Tap.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency Kotlin. Please download and install Kotlin to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.16.5.jar:git-Paper-467]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.5.jar:git-Paper-467]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.5.jar:git-Paper-467]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-467]        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-467]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[06:22:47 ERROR]: Could not load 'plugins\Psychics.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency Kotlin. Please download and install Kotlin to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.16.5.jar:git-Paper-467]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.5.jar:git-Paper-467]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.5.jar:git-Paper-467]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-467]        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-467]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[06:22:47 ERROR]: Could not load 'plugins\InvFX.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency Kotlin. Please download and install Kotlin to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.16.5.jar:git-Paper-467]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.5.jar:git-Paper-467]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.5.jar:git-Paper-467]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-467]        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-467]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[06:22:47 INFO]: [WorldEdit] Loading WorldEdit v7.2.2+fc3c499
[06:22:48 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@6e5efbf]
[06:22:48 INFO]: [ProtocolLib] Loading ProtocolLib v4.6.0-SNAPSHOT-b494
[06:22:48 INFO]: Server permissions file permissions.yml is empty, ignoring it
[06:22:48 INFO]: [WorldEdit] Enabling WorldEdit v7.2.2+fc3c499
[06:22:48 INFO]: WEPIF: Using the Bukkit Permissions API.
[06:22:49 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_16_R3 as the Bukkit adapter
[06:22:49 INFO]: [ProtocolLib] Enabling ProtocolLib v4.6.0-SNAPSHOT-b494
[06:22:49 INFO]: [ProtocolLib] Started structure compiler thread.
[06:22:49 INFO]: Preparing level "world"
[06:22:52 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[06:22:53 WARN]: Unable to find spawn biome
[06:22:53 WARN]: Unable to find spawn biome
[06:22:54 INFO]: Preparing start region for dimension minecraft:overworld
[06:22:54 INFO]: Loaded 0 spawn chunks for world world
[06:22:54 INFO]: Preparing spawn area: 0%
[06:22:54 INFO]: Time elapsed: 412 ms
[06:22:54 INFO]: Preparing start region for dimension minecraft:the_nether
[06:22:54 INFO]: Loaded 0 spawn chunks for world world_nether
[06:22:54 INFO]: Preparing spawn area: 0%
[06:22:54 INFO]: Time elapsed: 230 ms
[06:22:54 INFO]: Preparing start region for dimension minecraft:the_end
[06:22:54 INFO]: Loaded 0 spawn chunks for world world_the_end
[06:22:54 INFO]: Preparing spawn area: 0%
[06:22:55 INFO]: Preparing spawn area: 0%
[06:22:55 INFO]: Time elapsed: 571 ms
[06:22:55 INFO]: Running delayed init tasks
[06:22:55 INFO]: Done (8.774s)! For help, type "help"
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Please update the version of Java you use to run Paper
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] * to at least Java 11. When Paper for Minecraft 1.17 is
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] * released support for versions of Java before 11 will
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] * be dropped.
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Current Java version: 1.8.0_271
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Check this forum post for more information:
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] *   https://papermc.io/java11
[06:22:55 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[06:22:55 INFO]: Timings Reset
>

**Comment by monun** [comment]
JDK11
