### ISSUE TITLE
서버 구동 버그

### ISSUE THREAD

**Issue by chipppppp** [monun/psychics#31]
[21:20:32 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Unable to inject channel futures.
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:223)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:887)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:387)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443)
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:277)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 1, banned: 0], return={
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: input instanceof class java.net.InetAddress, Index: 0}, {Type: input instanceof int, Index: 1}], paramCount=2}],
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class net.minecraft.server.dedicated.DedicatedServer, Index: null}], paramCount=1}]
  }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getServerConnectionClass(MinecraftReflection.java:1416)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:120)
        ... 11 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@1a7a0b27[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5cc976ae
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@32f7c3a
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@2e1f8cb4
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@64768963
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@739def45
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0-SNAPSHOT-b492, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@5903d45d
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-182,minecraftVersion=1.17.1}
        library=ProtocolLib v4.6.0-SNAPSHOT-b492
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@15155220
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@40a15029
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@251d6c61
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.17.1)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@18e1f6ce[
      statistics=<null>
      backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@520bdde3
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5cc976ae
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@1c3bcda7
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@440caf62
      commandProtocol=com.comphenix.protocol.CommandProtocol@53cc76ab
      commandPacket=com.comphenix.protocol.CommandPacket@5f244df4
      commandFilter=com.comphenix.protocol.CommandFilter@1db0f542
      packetLogging=com.comphenix.protocol.PacketLogging@3ce63e29
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@c2f6e30
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-182,minecraftVersion=1.17.1}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@7199d9ac
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0-SNAPSHOT-b492, pluginEnabled=true, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@66035404
    ]
  Version:
    ProtocolLib v4.6.0-SNAPSHOT-b492
  Java Version:
    16.0.2
  Server:
    git-Paper-182 (MC: 1.17.1)
    
    라고뜨는데 어떻게 해야할까요

**Comment by dytroInc** [comment]
ProtocolLib 오류군요. 해당 오류는 여기 말고 https://github.com/dmulloy2/ProtocolLib/issues 에서 하는 게 맞습니다.
그리고 능력자 때문에 ProtocolLib이 필요하면, 넣을 필요 없습니다.

**Comment by chipppppp** [comment]
> ProtocolLib 오류군요. 해당 오류는 여기 말고 https://github.com/dmulloy2/ProtocolLib/issues 에서 하는 게 맞습니다.
> 그리고 능력자 때문에 ProtocolLib이 필요하면, 넣을 필요 없습니다.

버전까지 변경 했는데 왜 [10:16:39 ERROR]: Could not load 'plugins\psychics-2.0.0-SNAPSHOT.jar' in folder 'plugins' 라고 뜰까요 ㅠㅠ

**Comment by qogusdn1017** [comment]
최신 버전으로 직접 빌드하여 넣어주세요.

이슈 닫아주세요.
