### ISSUE TITLE
능력로드가안돼요

### ISSUE THREAD

**Issue by sunonnnn** [monun/psychics#42]
[12:32:48 WARN]: java.lang.IllegalStateException: Not found ability com.github.noonmaru.bomber
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:224)
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.PsychicManager.reload$psychics_common(PsychicManager.kt:62)
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.plugin.PsychicPlugin.reloadPsychics(PsychicPlugin.kt:114)
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:101)
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:41)
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[12:32:48 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:32:48 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:32:48 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832)
[12:32:48 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2169)
[12:32:48 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1980)
[12:32:48 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1961)
[12:32:48 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:32:48 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:32:48 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[12:32:48 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:32:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:32:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[12:32:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[12:32:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1458)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[12:32:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[12:32:48 WARN]: [Psychics] Failed to load Psychic sample.yml
[12:32:48 WARN]: java.lang.IllegalStateException: Not found ability ability-storm-breaker
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:224)
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.PsychicManager.reload$psychics_common(PsychicManager.kt:62)
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.plugin.PsychicPlugin.reloadPsychics(PsychicPlugin.kt:114)
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:101)
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:41)
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[12:32:48 WARN]:        at Psychics.jar//com.github.noonmaru.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[12:32:48 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:32:48 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:32:48 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832)
[12:32:48 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2169)
[12:32:48 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1980)
[12:32:48 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1961)
[12:32:48 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:32:48 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:32:48 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[12:32:48 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:32:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:32:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[12:32:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[12:32:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1458)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[12:32:48 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[12:32:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[12:32:48 WARN]: [Psychics] Failed to load Psychic storm-breaker.yml

**Comment by qogusdn1017** [comment]
noonmaru는 사용하지 않으므로 현재 monun에서 직접 빌드하여 사용하시거나 releases를 기다려 주세요.

이슈 닫아주세요.

**Comment by heisenberg-cat** [comment]
이슈 닫아주세요
