### ISSUE TITLE
서버 열던 도중

### ISSUE THREAD

**Issue by jini5012** [monun/psychics#48]
Could not load 'plugins\psychics-2.0.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[patched_1.17.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.17.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:404) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:276) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more

이게 떴습니다

**Comment by dytroInc** [comment]
어떤 방식으로 빌드를 진행했죠?

**Comment by jini5012** [comment]
그냥 intellij로 복사 해서 gradlew clean jar로요

**Comment by jini5012** [comment]
근데 영상보면 intellij로 서버열던데 그건 어떻게하나요?
