### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Ricepiggy** [monun/psychics#63]
**[09:55:55 WARN]: java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
[09:55:55 WARN]:        at com.github.monun.invfx.InvStage.<init>(InvStage.kt:31)
[09:55:55 WARN]:        at com.github.monun.invfx.internal.InvSceneImpl.<init>(InvSceneImpl.kt:30)
[09:55:55 WARN]:        at com.github.monun.invfx.builder.InvSceneBuilder.<init>(InvSceneBuilder.kt:33)
[09:55:55 WARN]:        at com.github.monun.invfx.InvFX.scene(InvFX.kt:29)
[09:55:55 WARN]:        at com.github.monun.psychics.invfx.InvPsychic.create(InvPsychic.kt:20)
[09:55:55 WARN]:        at com.github.monun.psychics.command.CommandPsychic.info(CommandPsychic.kt:109)
[09:55:55 WARN]:        at com.github.monun.psychics.command.CommandPsychic.access$info(CommandPsychic.kt:41)
[09:55:55 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$4$2$1.invoke(CommandPsychic.kt:77)
[09:55:55 WARN]:        at com.github.monun.psychics.command.CommandPsychic$register$1$4$2$1.invoke(CommandPsychic.kt:41)
[09:55:55 WARN]:        at com.github.monun.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[09:55:55 WARN]:        at com.github.monun.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[09:55:55 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:55:55 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[09:55:55 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1918)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1729)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
[09:55:55 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[09:55:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[09:55:55 WARN]: Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
[09:55:55 WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
[09:55:55 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171)
[09:55:55 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[09:55:55 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[09:55:55 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[09:55:55 WARN]:        ... 30 more

/psychics info sample
을 치니까 저렇게 버그가나네요**

**Comment by qogusdn1017** [comment]
네 버그 아닙니다

**Comment by Ricepiggy** [comment]
버그 아니면 뭔

**Comment by Ricepiggy** [comment]
그럼 해결방법은 없나요

**Comment by patrick-choe** [comment]
Psychics는 1.17.1에서 사용해주세요!

**Comment by Ricepiggy** [comment]
넵 감사합니다
