### ISSUE TITLE
/psychics info 사용시 오류 발생

### ISSUE THREAD

**Issue by myoun** [monun/psychics#7]
```
[22:41:09 INFO]: myoung2 issued server command: /psy info
[22:41:09 WARN]: java.lang.NoClassDefFoundError: com/github/noonmaru/invfx/InvFX
[22:41:09 WARN]:        at com.github.noonmaru.psychics.invfx.InvPsychic.create(InvPsychic.kt:20)
[22:41:09 WARN]:        at com.github.noonmaru.psychics.command.CommandPsychic.info(CommandPsychic.kt:109)
[22:41:09 WARN]:        at com.github.noonmaru.psychics.command.CommandPsychic.access$info(CommandPsychic.kt:41)
[22:41:09 WARN]:        at com.github.noonmaru.psychics.command.CommandPsychic$register$1$4$3.invoke(CommandPsychic.kt:85)
[22:41:09 WARN]:        at com.github.noonmaru.psychics.command.CommandPsychic$register$1$4$3.invoke(CommandPsychic.kt:41)
[22:41:09 WARN]:        at com.github.noonmaru.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[22:41:09 WARN]:        at com.github.noonmaru.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[22:41:09 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:41:09 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[22:41:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2176)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1991)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1944)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1392)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127)
[22:41:09 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[22:41:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[22:41:09 WARN]: Caused by: java.lang.ClassNotFoundException: com.github.noonmaru.invfx.InvFX
[22:41:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153)
[22:41:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[22:41:09 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[22:41:09 WARN]:        ... 27 more
```

**Comment by myoun** [comment]
![image](https://user-images.githubusercontent.com/76814120/118991066-5f603f00-b9be-11eb-81a9-c2d804c37dd9.png)
현재 플러그인 모두 다 들어가있습니다.

**Comment by myoun** [comment]
원인 찾았습니다.

원인 : 현재 InvFX 플러그인의 패키지가 com.github.monun이지만, 플러그인에서 불러올때, com.github.noonmaru로 불러옴

**Comment by myoun** [comment]
최신 버전의 psychics 플러그인 사용을 위해 github release에 1.0.2 버전을 올려주세요.

**Comment by myoun** [comment]
invfx update
https://github.com/monun/invfx/releases/tag/2.1.0

**Comment by qogusdn1017** [comment]
Please close the issue.
